- name: apt-transport-https is present
  apt:
    name: apt-transport-https
    state: latest
    force: yes
  tags: [docker]

- name: Add hypriot repository apt key
  apt_key: url=https://packagecloud.io/gpg.key

- name: Add hypriot repository to apt sources
  apt_repository:
    repo: "deb https://packagecloud.io/Hypriot/Schatzkiste/debian/ jessie main"
    state: present
  tags: [docker]

- name: Update apt cache
  apt: update_cache=yes
  
- name: Docker Hypriot is present
  apt:
    name: docker-engine
    state: latest
    force: yes
  tags: [docker]
  
- name: Python is present
  apt:
    name: python
    state: latest
    force: yes
  tags: [docker]

- name: Outdated python-pip is absent
  apt:
    name: python-pip
    state: absent
  tags: [docker]

- name: Python setuptools are present
  apt:
    name: python-setuptools
    state: latest
    force: yes
  tags: [docker]

- name: Latest python-pip is present
  easy_install:
    name: pip
    state: latest
  tags: [docker]

- name: Debian docker-py is present
  pip:
    name: docker-py
    state: present
  tags: [docker]

- name: Debian files are present
  template:
    src: docker.cfg
    dest: /etc/default/docker
  register: copy_result
  tags: [docker]

- name: Debian Daemon is reloaded
  command: systemctl daemon-reload
  when: copy_result|changed
  tags: [docker]

- name: Docker service is restarted
  service:
    name: docker
    enabled: yes
    state: restarted
  tags: [docker]